name: CI Pipeline
on: [push, pull_request]

jobs:
  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    container: gcc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix repository ownership
        run: git config --global --add safe.directory /__w/genpw/genpw
      - name: Install dependencies
        run: apt-get update && apt-get install -y git clang-format
      - name: Check formatting
        run: |
          find . -name '*.c' -o -name '*.h' | xargs clang-format -i --verbose
          git diff --ignore-submodules --exit-code

  build:
    name: Build
    needs: format_check
    runs-on: ubuntu-latest
    container: gcc:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: |
          make clean
          make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/
          if-no-files-found: error
          retention-days: 1